# Generated by Django 2.2.4 on 2019-08-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateField(auto_now_add=True,),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
