# Generated by Django 2.2.4 on 2019-08-16 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190816_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.python manage.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
