# Generated by Django 2.2.4 on 2019-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20190816_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='quetions',
            field=models.ForeignKey(on_delete='models.CASCADE', to='poll.Question'),
        ),
    ]
